// Code generated by 'banks apply'; DO NOT EDIT.

package resources

import (
	"github.com/autopilothq/banks/contract"
	"github.com/autopilothq/banks/protocol/marshalable"
	"github.com/autopilothq/banks/types"

	"github.com/example/taranaki/protocols"
	rodata "github.com/example/taranaki/resourcefile"

	// register resources and load their protocols
	_ "github.com/example/taranaki/resources/ApiKeys"
	protocolApiKeys "github.com/example/taranaki/resources/ApiKeys/protocol"
)

func init() {
	lock, err := rodata.GetROLockfile()
	if err != nil {
		panic(err)
	}

	contract.Provides(
		lock.Resources,
		lock.Resource,
		protocols.Read,
		MsgIDFromReqBody,
	)
}

// MsgIDFromReqBody looks up a message ID for a request body type. It is used
// by banks dispatch.
func MsgIDFromReqBody(reqBody marshalable.Body) (types.MessageID, bool) {
	switch reqBody.(type) {

	case *protocolApiKeys.GenerateRequest:
		return types.MessageID(65537), true
	case *protocolApiKeys.EnableRequest:
		return types.MessageID(65538), true
	case *protocolApiKeys.DisableRequest:
		return types.MessageID(65539), true
	case *protocolApiKeys.GetRequest:
		return types.MessageID(65540), true

	default:
		return types.MessageID(0), false
	}
}
